### ISSUE TITLE
Share Routes

### ISSUE THREAD

**Issue by panchocuetodaniel** [Arquisoft/viade_es4c#54]

**Comment by CarlosMenchacaUO258650** [comment]
Pasos serían:

 Para compartir la ruta:
 1. Pulsar boton compartir
 2. Coger la ruta actual
 3. Recorrer la lista de amigos
 3.1. Para cada amigo, pegar la ruta actual en el archivo que guarda las rutas compartidas
 
Para listar las rutas compartidas:
 1. Coger mi archivo de rutas compartidas y listarlas

**Comment by christianpe98** [comment]
Also we have to manage the notifications to share routes

**Comment by christianpe98** [comment]
# Summary 
(We are going to follow the inrupt approach)
Suppose that user A wants to share a route with user B.

1. A notification is sent to user B notifying that user A wants to share a route with him.
2. User B can accept or reject the shared route.
2.1 If user B accepts the route it will be added to the routes shared with him. In addition, user A will be notified that user B has accepted his route.
2.2 If user B denies the route, user A will be notified that user B did not accept his route.

# Tasks

-  Be able to send notifications between users.(#77 )
-  Be able to receive a notification and display it (#77 )
- [x]  Give read permissions on the shared route to user B
- [x] Create a file on user B's pod that stores the URIs of the routes shared with him and add the URI of the shared route. If the file already exists just add the route. (schema:hasPart)
- [x] All routes shared with a user must be displayed in an application window.

**Comment by christianpe98** [comment]
# Update flow to share
(We are going to follow the inrupt approach)
Suppose that user A wants to share a route with user B.

A notification is sent to user B notifying that user A wants to share a route with him.
User B can accept or reject the shared route.
2.1 If user B accepts the route it will be added to the routes shared with him. ~~In addition, user A will be notified that user B has accepted his route~~.
~~2.2 If user B denies the route, user A will be notified that user B did not accept his route.~~
